# https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Configuration-Changelog
# https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3.0-Configuration-Changelog
debug: false

server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
    basedir: /home/temp
  servlet:
    context-path: ''
    session:
      tracking-modes: cookie
      cookie:
        http-only: true
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: true
    path: /error

#logging:
#  level:
#    root: info
#    io.github: debug
#    #    org.springframework: warn
#    org.springframework: info

mybatis-plus:
  #  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: io.github.entity
  # 自定义类型转换处理器包名
  type-handlers-package: io.github.common.typehandler
  check-config-location: true
  configuration:
    cache-enabled: false
    log-prefix: bootplus.dao.
    map-underscore-to-camel-case: true
  global-config:
    banner: true
    db-config:
      id-type: auto
      table-underline: true

spring:
  application:
    name: ${application.name}
  aop:
    auto: true
    proxy-target-class: true
  profiles:
  # 生产环境
  #    active: prd
  #    active: dev
  cache:
    ehcache:
      config: classpath:/ehcache-core.xml
  #    type: EHCACHE
  datasource:
    #    filters: stat,wall,log4j
    filters: stat,wall,slf4j
    initial-size: 5
    max-active: 20
    maxPoolPreparedStatementPerConnectionSize: 20
    max-wait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 5
    poolPreparedStatements: true
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/bootplus?serverTimezone=GMT%2B8&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;password=${spring.datasource.password}
    validation-query: SELECT 1 FROM DUAL
  freemarker:
    allow-request-override: false
    cache: false
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: rc
    settings:
      number_format: 0.##
      # freemarker.core.Configurable#setSetting
      # freemarker.template.Configuration#setSetting
      tag_syntax: auto_detect
    suffix: .ftl
    check-template-location: true
    template-loader-path:
      - classpath:/templates/
  messages:
    encoding: UTF-8
  resources:
    static-locations:
      - classpath:/META-INF/resources/
      - classpath:/resources/
      - classpath:/statics/
      - classpath:/public/
  data:
    jpa:
      repositories:
        enabled: false
    redis:
      repositories:
        enabled: false
  redis:
    # TODO 接入
    timeout: 3000
    password: test
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  # Spring Security Default user name and password
  security:
    user:
      name: admin
      password: admin
      roles: admin
  jpa:
    open-in-view: false

management:
  endpoint:
    health:
      show-details: always
  server:
  #    port: 8090
  #    servlet:
  #      context-path: /monitor
  endpoints:
    web:
      # io.github.config.ActuatorWebSecurityConfig
      base-path: /admin/monitor

################################### 程序自定义配置 ###################################

application:
  #  管理员ID
  admin-id: 1
  name: @project.artifactId@
  version: @project.version@
  url: @project.url@
  description: @project.description@
  blog: @blog.url@
  logs:
    level: DEBUG
    path: @project.basedir@/../logs
  # 自定义线程池配置
  thread-pool:
    core-pool-size: 3
    max-pool-size: 2000
    queue-capacity: 200
    keep-alive-seconds: 3000
    thread-name-prefix: ${application.name:zhousiwei}-task-
  mvc:
    view-resolves:
      - {urlPath: '/',viewName: 'redirect:/admin'}
  file-config:
    # 文件上传保存路径
    upload-path: /home/fulei/zhousiwei/upload
  junit-env:
    admin-name: admin
    admin-pwd: admin
