server:
  contextPath: ''
  port: 80
  tomcat:
    uri-encoding: UTF-8
  session:
    tracking-modes: cookie
    cookie:
      http-only: true

logging:
  level:
    root: info
    io.github: debug
    #    org.springframework: warn
    org.springframework: info

mybatis-plus:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    log-prefix: bootplus.dao.
  global-config:
    db-column-underline: true
    field-strategy: 0
    id-type: 0
    refresh-mapper: true
  mapper-locations: classpath:/mapper/*Dao.xml
  typeAliasesPackage: io.github.entity

spring:
  profiles:
    # 生产环境
    #    active: prd
    active: dev
  datasource:
    #    filters: stat,wall,log4j
    filters: stat,wall,slf4j
    initialSize: 5
    maxActive: 20
    maxPoolPreparedStatementPerConnectionSize: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 5
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/bootplus?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;password=${spring.datasource.password}
    driverClassName: com.mysql.jdbc.Driver
    validationQuery: SELECT 1 FROM DUAL
  freemarker:
    allow-request-override: false
    cache: false
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: rc
    settings:
      number_format: 0.##
    suffix: .ftl
    check-template-location: true
    template-loader-path: classpath:/WEB-INF/templates
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      maxFileSize: 10Mb
      maxRequestSize: 10Mb
  messages:
    encoding: UTF-8
  resources:
    static-locations: classpath:/statics
  aop:
    auto: true
    proxy-target-class: true

management:
  #  context-path: /monitor
  security:
    # 权限拦截
    enabled: true

security:
  user:
    name: admin
    password: admin
    role: admin
  basic:
    path: ${management.context-path:/monitor}/**
    enabled: true

# 自定义线程池
thread-pool:
#  core-pool-size: 3
#  max-pool-size: 2000
#  queue-capacity: 200
#  keep-alive-seconds: 2000
#  thread-name-prefix: boot-task-
